export enum STATUS {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED",
    PENDING_CREATION = "PENDING_CREATION_APPROVAL",
    PENDING_UPDATE = "PENDING_UPDATE_APPROVAL",
}

export enum VerificationStatus {
    COMPLETED = "VERIFICATION_COMPLETED",
    FAILED = "VERIFICATION_NOT_COMPLETED",
    REJECTED = "VERIFICATION_REJECTED",
    SUCCESSFUL = "VERIFICATION_SUCCESSFUL",
}

export enum VerificationOptions {
    NIN = "NIN",
    DRIVERS_LICENSE = "DRIVERS_LICENSE",
    INTERNATIONAL_PASSPORT = "INTERNATIONAL_PASSPORT",
    NO_OPTION = "NO_OPTION",
}

export enum VerificationStages {
    NO_VERIFICATION = "NO_VERIFICATION",
    LIVELINESS_DETECTED = "LIVELINESS_DETECTED",
    FACE_VERIFIED = "FACE_VERIFIED",
    BIODATA_VERIFIED = "BIODATA_VERIFIED",
    FINGERPRINT_VERIFIED = "FINGERPRINT_VERIFIED",
    BASIC_DETAILS_VERIFIED = "BASIC_DETAILS_VERIFIED",
}

export enum RequestMethod {
    POST = "POST",
    PUT = "PUT",
}
